export const openWeatherCityOptions = [
  { label: "An Giang", value: "An Giang,VN" },
  { label: "Bac Ninh", value: "Bac Ninh,VN" },
  { label: "Ca Mau", value: "Ca Mau,VN" },
  { label: "Can Tho", value: "Can Tho,VN" },
  { label: "Cao Bang", value: "Cao Bang,VN" },
  { label: "Da Nang", value: "Da Nang,VN" },
  { label: "Dak Lak", value: "Dak Lak,VN" },
  { label: "Dien Bien", value: "Dien Bien,VN" },
  { label: "Dong Nai", value: "Dong Nai,VN" },
  { label: "Dong Thap", value: "Dong Thap,VN" },
  { label: "Gia Lai", value: "Gia Lai,VN" },
  { label: "Ha Noi", value: "Hanoi,VN" },
  { label: "Ha Tinh", value: "Ha Tinh,VN" },
  { label: "Hai Phong", value: "Hai Phong,VN" },
  { label: "Ho Chi Minh City", value: "Ho Chi Minh City,VN" },
  { label: "Hue", value: "Hue,VN" },
  { label: "Hung Yen", value: "Hung Yen,VN" },
  { label: "Khanh Hoa", value: "Khanh Hoa,VN" },
  { label: "Lai Chau", value: "Lai Chau,VN" },
  { label: "Lam Dong", value: "Lam Dong,VN" },
  { label: "Lang Son", value: "Lang Son,VN" },
  { label: "Lao Cai", value: "Lao Cai,VN" },
  { label: "Nghe An", value: "Nghe An,VN" },
  { label: "Ninh Binh", value: "Ninh Binh,VN" },
  { label: "Phu Tho", value: "Phu Tho,VN" },
  { label: "Quang Ninh", value: "Quang Ninh,VN" },
  { label: "Quang Ngai", value: "Quang Ngai,VN" },
  { label: "Quang Tri", value: "Quang Tri,VN" },
  { label: "Son La", value: "Son La,VN" },
  { label: "Tay Ninh", value: "Tay Ninh,VN" },
  { label: "Thai Nguyen", value: "Thai Nguyen,VN" },
  { label: "Thanh Hoa", value: "Thanh Hoa,VN" },
  { label: "Tuyen Quang", value: "Tuyen Quang,VN" },
  { label: "Vinh Long", value: "Vinh Long,VN" },
];
